# Generated by Django 4.2.6 on 2024-01-15 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0009_alter_category_name_alter_subject_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('1年前期', '1年前期'), ('1年後期', '1年後期'), ('2年前期', '2年前期'), ('2年後期', '2年後期'), ('3年前期', '3年前期'), ('3年後期', '3年後期'), ('4年前期', '4年前期'), ('4年後期', '4年後期')], max_length=5, verbose_name='学年')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
    ]
