# Generated by Django 4.2.6 on 2023-12-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_subject_credit_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('required_credit', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='requiredment_credit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crud.category'),
        ),
    ]
