# Generated by Django 4.2.6 on 2024-01-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_student_delete_studentuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentCategory',
        ),
    ]
