# Generated by Django 4.2.6 on 2024-01-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_student_faculty_student_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('経済学部', '経済学部'), ('経営学部', '経営学部'), ('法学部', '法学部')], default='経営学部', max_length=5, verbose_name='学科'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('1年前期', '1年前期'), ('1年後期', '1年後期'), ('2年前期', '2年前期'), ('2年後期', '2年後期'), ('3年前期', '3年前期'), ('3年後期', '3年後期'), ('4年前期', '4年前期'), ('4年後期', '4年後期')], default='4前期', max_length=5, verbose_name='学年と学期'),
        ),
    ]
