# Generated by Django 4.2.6 on 2024-01-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_remove_student_faculty_remove_student_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('経済学部', '経済学部'), ('経営学部', '経営学部'), ('法学部', '法学部')], default='経営学部', max_length=5, verbose_name='学部'),
        ),
    ]
