# Generated by Django 4.2.6 on 2024-01-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_remove_student_department_student_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('経済学部', '経済学部'), ('経営学部', '経営学部'), ('法学部', '法学部')], default='経営学部', max_length=5, verbose_name='学科'),
        ),
    ]
