# Generated by Django 4.2.6 on 2024-01-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_alter_student_department_alter_student_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='required_category',
            field=models.BooleanField(default=False, verbose_name='必修科目'),
        ),
    ]
