# Generated by Django 4.2.6 on 2024-01-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_subject_required_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='required_category',
            new_name='is_required',
        ),
    ]
