# Generated by Django 4.2.6 on 2023-10-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detail',
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
